services:
  - type: web
    name: tts-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TORCH_FORCE_WEIGHTS_ONLY_LOAD
        value: "0"
    plan: free
